/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/office/notices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotice"];
        put: operations["updateNotice"];
        post?: never;
        delete: operations["deleteNotice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateMeeting"];
        post?: never;
        delete: operations["deleteMeeting"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateGroup"];
        post?: never;
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/group-contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateGroupContact"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/districts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateDistrict"];
        post?: never;
        delete: operations["deleteDistrict"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/content-pages/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["togglePublishContentPage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/admin-users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotices"];
        put?: never;
        post: operations["createNotice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMeetings"];
        put?: never;
        post: operations["createMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/meetings/backfill-coordinates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["backfillMissingCoordinates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGroups"];
        put?: never;
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/groups/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGroupBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/group-contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGroupContacts"];
        put?: never;
        post: operations["createGroupContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDistricts"];
        put?: never;
        post: operations["createDistrict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/content-pages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateContentPage"];
        delete: operations["deleteContentPage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/content-pages/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadContentPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["handleFileUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/admin-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsers"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/content-pages/{id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateContentMetadata"];
        trace?: never;
    };
    "/api/public/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotices_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/notices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotice_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMeetings_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDistricts_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/content-pages/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContentPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/attachments/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/content-pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContentPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NoticeRequest: {
            title: string;
            bodyHtml: string;
            bodyJson: string;
            published: boolean;
            /** Format: date-time */
            publishedAt?: string;
            attachmentIds?: number[];
        };
        ApiResponseNoticeData: {
            data?: components["schemas"]["NoticeData"];
        };
        AttachmentSummaryData: {
            /** Format: int64 */
            id?: number;
            originalName?: string;
            url?: string;
            /** Format: int64 */
            fileSize?: number;
        };
        NoticeData: {
            /** Format: int64 */
            id?: number;
            title?: string;
            bodyHtml?: string;
            bodyJson?: string;
            published?: boolean;
            /** Format: date-time */
            publishedAt?: string;
            attachments?: components["schemas"]["AttachmentSummaryData"][];
        };
        MeetingRequest: {
            /** Format: int64 */
            groupId: number;
            locationDetail: string;
            locationAddress: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            contactPhoneOverride?: string;
            dayOfWeek: string;
            startTime: string;
            type: string;
            active: boolean;
        };
        ApiResponseMeetingData: {
            data?: components["schemas"]["MeetingData"];
        };
        MeetingData: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            groupId?: number;
            groupName?: string;
            province?: string;
            locationDetail?: string;
            locationAddress?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            contactPhoneOverride?: string;
            dayOfWeek?: string;
            startTime?: string;
            type?: string;
            active?: boolean;
        };
        GroupRequest: {
            /** Format: int64 */
            districtId: number;
            name: string;
            notice?: string;
        };
        ApiResponseGroupData: {
            data?: components["schemas"]["GroupData"];
        };
        GroupData: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            districtId?: number;
            name?: string;
            notice?: string;
        };
        PostalContactRequest: {
            recipient?: string;
            postalCode?: string;
            roadAddress?: string;
            detailAddress?: string;
        };
        UpdateGroupContactRequest: {
            phone: string;
            email?: string;
            postalContact?: components["schemas"]["PostalContactRequest"];
        };
        ApiResponseGroupContactData: {
            data?: components["schemas"]["GroupContactData"];
        };
        GroupContactData: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            groupId?: number;
            phone?: string;
            email?: string;
            postalContact?: components["schemas"]["PostalContactData"];
        };
        PostalContactData: {
            recipient?: string;
            postalCode?: string;
            roadAddress?: string;
            detailAddress?: string;
        };
        DistrictRequest: {
            name: string;
        };
        ApiResponseDistrictData: {
            data?: components["schemas"]["DistrictData"];
        };
        DistrictData: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        ApiResponseVoid: {
            data?: Record<string, never>;
        };
        UpdateUserRequest: {
            displayName: string;
            /** @enum {string} */
            role: "SYSTEM_ADMIN" | "MANAGER" | "STAFF";
            /** @enum {string} */
            status: "PENDING_APPROVAL" | "ACTIVE" | "SUSPENDED";
            password?: string;
            grantedPermissions?: string[];
        };
        ApiResponseUserData: {
            data?: components["schemas"]["UserData"];
        };
        UserData: {
            /** Format: int64 */
            id?: number;
            email?: string;
            displayName?: string;
            role?: string;
            roleLabel?: string;
            status?: string;
            statusLabel?: string;
            editable?: boolean;
            grantedPermissions?: string[];
            effectivePermissions?: string[];
            /** Format: date-time */
            approvedAt?: string;
            /** Format: int64 */
            approvedByUserId?: number;
            approvedByLabel?: string;
            /** Format: date-time */
            lastLoginAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            updatedByUserId?: number;
            updatedByLabel?: string;
            managementHistory?: components["schemas"]["UserHistoryEventData"][];
        };
        UserHistoryEventData: {
            /** Format: int64 */
            id?: number;
            eventType?: string;
            title?: string;
            detail?: string;
            /** Format: date-time */
            happenedAt?: string;
            /** Format: int64 */
            actorUserId?: number;
            actorLabel?: string;
        };
        ApiResponseCoordinateBackfillResult: {
            data?: components["schemas"]["CoordinateBackfillResult"];
        };
        CoordinateBackfillItem: {
            /** Format: int64 */
            meetingId?: number;
            /** Format: int64 */
            groupId?: number;
            groupName?: string;
            locationAddress?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /** @enum {string} */
            status?: "READY" | "UPDATED" | "FAILED";
            message?: string;
        };
        CoordinateBackfillResult: {
            dryRun?: boolean;
            /** Format: int32 */
            totalCandidateCount?: number;
            /** Format: int32 */
            resolvedCount?: number;
            /** Format: int32 */
            updatedCount?: number;
            /** Format: int32 */
            failedCount?: number;
            items?: components["schemas"]["CoordinateBackfillItem"][];
        };
        GroupCompositeRequest: {
            name?: string;
            /** Format: int64 */
            districtId?: number;
            notice?: string;
            contact?: components["schemas"]["GroupContactRequest"];
            meetings?: components["schemas"]["MeetingCompositeRequest"][];
        };
        GroupContactRequest: {
            phone?: string;
            email?: string;
            postalContact?: components["schemas"]["PostalContactInput"];
        };
        MeetingCompositeRequest: {
            locationDetail?: string;
            locationAddress?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            contactPhoneOverride?: string;
            dayOfWeek?: string;
            startTime?: string;
            type?: string;
            active?: boolean;
        };
        PostalContactInput: {
            recipient?: string;
            postalCode?: string;
            roadAddress?: string;
            detailAddress?: string;
        };
        ApiResponseLong: {
            /** Format: int64 */
            data?: number;
        };
        CreateGroupContactRequest: {
            /** Format: int64 */
            groupId: number;
            phone: string;
            email?: string;
            postalContact?: components["schemas"]["PostalContactRequest"];
        };
        ApiResponseContentPageData: {
            data?: components["schemas"]["ContentPageData"];
        };
        ContentPageData: {
            /** Format: int64 */
            id?: number;
            key?: string;
            title?: string;
            published?: boolean;
            originalFileName?: string;
            attachments?: components["schemas"]["AttachmentSummaryData"][];
        };
        ApiResponseAttachmentData: {
            data?: components["schemas"]["AttachmentData"];
        };
        AttachmentData: {
            /** Format: int64 */
            id?: number;
            originalName?: string;
            url?: string;
            /** Format: int64 */
            fileSize?: number;
            contentType?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        AssetUploadResponse: {
            url?: string;
        };
        CreateUserRequest: {
            email: string;
            displayName: string;
            /** @enum {string} */
            role: "SYSTEM_ADMIN" | "MANAGER" | "STAFF";
            password: string;
            grantedPermissions?: string[];
        };
        RegisterRequest: {
            email: string;
            displayName: string;
            password: string;
        };
        ApiResponseRegistrationStatus: {
            data?: components["schemas"]["RegistrationStatus"];
        };
        RegistrationStatus: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            displayName?: string;
            role?: string;
            status?: string;
        };
        ApiResponseLogoutStatus: {
            data?: components["schemas"]["LogoutStatus"];
        };
        LogoutStatus: {
            success?: boolean;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        ApiResponseAuthStatus: {
            data?: components["schemas"]["AuthStatus"];
        };
        AuthStatus: {
            authenticated?: boolean;
            /** Format: int64 */
            userId?: number;
            email?: string;
            username?: string;
            displayName?: string;
            role?: string;
            status?: string;
            permissions?: string[];
        };
        MetadataUpdateRequest: {
            key?: string;
            title?: string;
            published?: boolean;
        };
        ApiResponseListPublicNoticeSummary: {
            data?: components["schemas"]["PublicNoticeSummary"][];
        };
        PublicNoticeSummary: {
            /** Format: int64 */
            id?: number;
            title?: string;
            /** Format: date-time */
            publishedAt?: string;
        };
        ApiResponsePublicNoticeData: {
            data?: components["schemas"]["PublicNoticeData"];
        };
        AttachmentSummary: {
            /** Format: int64 */
            id?: number;
            originalName?: string;
            url?: string;
            /** Format: int64 */
            fileSize?: number;
        };
        PublicNoticeData: {
            /** Format: int64 */
            id?: number;
            title?: string;
            bodyHtml?: string;
            /** Format: date-time */
            publishedAt?: string;
            attachments?: components["schemas"]["AttachmentSummary"][];
        };
        ApiResponseListMeetingSummary: {
            data?: components["schemas"]["MeetingSummary"][];
        };
        MeetingSummary: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            groupId?: number;
            groupName?: string;
            province?: string;
            /** @enum {string} */
            dayOfWeek?: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
            startTime?: string;
            /** @enum {string} */
            type?: "OPEN" | "CLOSED" | "NOTFIXED";
            locationDetail?: string;
            locationAddress?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /** Format: int64 */
            districtId?: number;
            /** Format: double */
            distanceKm?: number;
        };
        ApiResponseGroupDetail: {
            data?: components["schemas"]["GroupDetail"];
        };
        District: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        GroupDetail: {
            /** Format: int64 */
            id?: number;
            name?: string;
            district?: components["schemas"]["District"];
            contactPhone?: string;
            notice?: string;
            meetings?: components["schemas"]["GroupMeeting"][];
        };
        GroupMeeting: {
            /** Format: int64 */
            id?: number;
            contactPhone?: string;
            province?: string;
            /** @enum {string} */
            dayOfWeek?: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
            startTime?: string;
            /** @enum {string} */
            type?: "OPEN" | "CLOSED" | "NOTFIXED";
            locationDetail?: string;
            locationAddress?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
        };
        ApiResponseListPublicDistrictResponse: {
            data?: components["schemas"]["PublicDistrictResponse"][];
        };
        PublicDistrictResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        ApiResponsePublicContentPageData: {
            data?: components["schemas"]["PublicContentPageData"];
        };
        PublicContentPageData: {
            /** Format: int64 */
            id?: number;
            key?: string;
            title?: string;
            bodyHtml?: string;
            attachments?: components["schemas"]["AttachmentSummary"][];
        };
        ApiResponseListNoticeSummaryData: {
            data?: components["schemas"]["NoticeSummaryData"][];
        };
        NoticeSummaryData: {
            /** Format: int64 */
            id?: number;
            title?: string;
            published?: boolean;
            /** Format: date-time */
            publishedAt?: string;
        };
        ApiResponseListMeetingData: {
            data?: components["schemas"]["MeetingData"][];
        };
        ApiResponseListGroupData: {
            data?: components["schemas"]["GroupData"][];
        };
        ApiResponseListGroupContactData: {
            data?: components["schemas"]["GroupContactData"][];
        };
        ApiResponseListDistrictData: {
            data?: components["schemas"]["DistrictData"][];
        };
        ApiResponseListContentPageSummaryData: {
            data?: components["schemas"]["ContentPageSummaryData"][];
        };
        ContentPageSummaryData: {
            /** Format: int64 */
            id?: number;
            key?: string;
            title?: string;
            published?: boolean;
            originalFileName?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageAuditLogData: {
            data?: components["schemas"]["PageObject"];
        };
        AuditLogData: {
            /** Format: int64 */
            id?: number;
            entityType?: string;
            /** Format: int64 */
            entityId?: number;
            action?: string;
            diff?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            createdBy?: number;
            creatorEmail?: string;
            entityLabel?: string;
        };
        PageObject: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AuditLogData"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        PageableObject: {
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
        };
        SortObject: {
            sorted?: boolean;
            unsorted?: boolean;
            empty?: boolean;
        };
        ApiResponseUserWorkspaceData: {
            data?: components["schemas"]["UserWorkspaceData"];
        };
        PermissionOptionData: {
            key?: string;
            label?: string;
            description?: string;
        };
        RoleOptionData: {
            value?: string;
            label?: string;
        };
        UserWorkspaceData: {
            users?: components["schemas"]["UserData"][];
            creatableRoles?: components["schemas"]["RoleOptionData"][];
            staffGrantOptions?: components["schemas"]["PermissionOptionData"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getNotice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoticeData"];
                };
            };
        };
    };
    updateNotice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoticeData"];
                };
            };
        };
    };
    deleteNotice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMeetingData"];
                };
            };
        };
    };
    deleteMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupData"];
                };
            };
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateGroupContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupContactRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupContactData"];
                };
            };
        };
    };
    updateDistrict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DistrictRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDistrictData"];
                };
            };
        };
    };
    deleteDistrict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    togglePublishContentPage: {
        parameters: {
            query: {
                published: boolean;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserData"];
                };
            };
        };
    };
    getNotices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListNoticeSummaryData"];
                };
            };
        };
    };
    createNotice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoticeData"];
                };
            };
        };
    };
    getMeetings: {
        parameters: {
            query?: {
                groupId?: number;
                province?: string;
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMeetingData"];
                };
            };
        };
    };
    createMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMeetingData"];
                };
            };
        };
    };
    backfillMissingCoordinates: {
        parameters: {
            query?: {
                dryRun?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCoordinateBackfillResult"];
                };
            };
        };
    };
    getGroups: {
        parameters: {
            query?: {
                districtId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListGroupData"];
                };
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupData"];
                };
            };
        };
    };
    createGroupBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCompositeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    getGroupContacts: {
        parameters: {
            query?: {
                groupId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListGroupContactData"];
                };
            };
        };
    };
    createGroupContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupContactRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupContactData"];
                };
            };
        };
    };
    getDistricts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListDistrictData"];
                };
            };
        };
    };
    createDistrict: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DistrictRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDistrictData"];
                };
            };
        };
    };
    updateContentPage: {
        parameters: {
            query: {
                key: string;
                title: string;
                published: boolean;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseContentPageData"];
                };
            };
        };
    };
    deleteContentPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    uploadContentPage: {
        parameters: {
            query: {
                key: string;
                title: string;
                published?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseContentPageData"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttachmentData"];
                };
            };
        };
    };
    handleFileUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssetUploadResponse"];
                };
            };
        };
    };
    getUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserWorkspaceData"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserData"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRegistrationStatus"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLogoutStatus"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthStatus"];
                };
            };
        };
    };
    updateContentMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetadataUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseContentPageData"];
                };
            };
        };
    };
    getNotices_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPublicNoticeSummary"];
                };
            };
        };
    };
    getNotice_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePublicNoticeData"];
                };
            };
        };
    };
    getMeetings_1: {
        parameters: {
            query?: {
                province?: string[];
                dayOfWeek?: string;
                type?: "OPEN" | "CLOSED" | "NOTFIXED";
                districtId?: number;
                keyword?: string;
                latitude?: number;
                longitude?: number;
                radiusKm?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMeetingSummary"];
                };
            };
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupDetail"];
                };
            };
        };
    };
    getDistricts_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPublicDistrictResponse"];
                };
            };
        };
    };
    getContentPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePublicContentPageData"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getContentPages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListContentPageSummaryData"];
                };
            };
        };
    };
    getAuditLogs: {
        parameters: {
            query: {
                entityType?: string;
                entityId?: number;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAuditLogData"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthStatus"];
                };
            };
        };
    };
}
