spring:
  application:
    name: aakorea-main
  datasource:
    url: jdbc:postgresql://localhost:5432/aakorea_main
    username: aakorea_admin
    password: aa1935
  jpa:
    hibernate:
      ddl-auto: update
app:
  auth:
    admin:
      username: ${AAKOREA_ADMIN_USERNAME:admin}
      password: ${AAKOREA_ADMIN_PASSWORD:password}
