spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aakorea_main
    username: aakorea_admin
    password: aa1935
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
