server:
  port: ${AAKOREA_SERVER_PORT:8081}
  forward-headers-strategy: framework

app:
  cors:
    allowed-origins:
      - https://maumtalk.win
      - https://www.maumtalk.win
      - http://localhost
      - http://127.0.0.1
      - http://localhost:8080
      - http://127.0.0.1:8080
      - http://localhost:5173
      - http://127.0.0.1:5173
